CREATE TABLE EMPLEADOS("ID" NUMBER(2), "NOMBRE" NVARCHAR2(100), "FECHANACI" DATE, "SALARIO" NUMBER(8,2), "ACTUALIZADO" DATE, "DIASTRABAJADOS" NUMBER(2,0));
SET DEFINE OFF;

INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('1','Tonya Vazques',to_date('01/06/80','DD/MM/RR'),'1200',to_date('17/10/18','DD/MM/RR'),'30');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('2','Mathews Robbins',to_date('23/02/85','DD/MM/RR'),'690',to_date('17/10/18','DD/MM/RR'),'25');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('3','Walton Vincent',to_date('22/05/80','DD/MM/RR'),'800',to_date('17/10/18','DD/MM/RR'),'25');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('4','Audra Wades',to_date('09/09/72','DD/MM/RR'),'1500',to_date('17/10/18','DD/MM/RR'),'20');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('5','Susanne Moody',to_date('05/10/95','DD/MM/RR'),'1100',to_date('17/10/18','DD/MM/RR'),'10');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('6','Stevenson Dickson',to_date('05/11/80','DD/MM/RR'),'420',to_date('17/10/18','DD/MM/RR'),'1');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('7','Hinton Cooper',to_date('26/12/73','DD/MM/RR'),'660',to_date('17/10/18','DD/MM/RR'),'5');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('8','Hahn Brown',to_date('28/02/89','DD/MM/RR'),'725',to_date('17/10/18','DD/MM/RR'),'18');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('9','Bennett Brady',to_date('31/05/91','DD/MM/RR'),'1200',to_date('17/10/18','DD/MM/RR'),'19');
INSERT INTO EMPLEADOS (ID, NOMBRE, FECHANACI, SALARIO, ACTUALIZADO, DIASTRABAJADOS) values ('10','Mueller Jimenez',to_date('28/05/81','DD/MM/RR'),'475',to_date('17/10/18','DD/MM/RR'),'20');
COMMIT;