CREATE OR REPLACE FUNCTION FN_EDAD_ACTUAL (FECHANACI IN DATE)
RETURN NUMBER IS

Edad NUMBER(3):=0;
BEGIN
	Edad:=TRUNC((TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD'))- TO_NUMBER(TO_CHAR(FECHANACI,'YYYYMMDD')))/10000);

	RETURN Edad;

	EXCEPTION
	WHEN OTHERS THEN
	Edad :=0;
	RETURN Edad;

END;
/