SET SERVEROUTPUT ON;

DECLARE

REG_EMPLEADO EMPLEADOS%ROWTYPE;

BEGIN
-- Solo permite 1 registro
SELECT * INTO REG_EMPLEADO FROM EMPLEADOS WHERE ID=5;
DBMS_OUTPUT.PUT_LINE(REG_EMPLEADO.NOMBRE);
DBMS_OUTPUT.PUT_LINE(REG_EMPLEADO.ID);
DBMS_OUTPUT.PUT_LINE(REG_EMPLEADO.SALARIO);
DBMS_OUTPUT.PUT_LINE(REG_EMPLEADO.ACTUALIZADO);

END;
/